name: Deploy Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: home
        run: npm install

      - name: Build site
        working-directory: home
        run: npm run build

      - name: Copy build output to /public
        run: |
          rm -rf public/*
          cp -r home/dist/* public/
          
      - name: Commit updated public folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public
          git commit -m "Deploy website" || echo "No changes to commit"
          git push