name: Deploy Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: home
        run: npm install

      - name: Build site
        working-directory: home
        run: npm run build

      - name: Copy build output to /public
        run: |
          rm -rf public/*
          mkdir -p public
          cp -r home/dist/* public/

      - name: Commit updated public folder
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add -A

          # Prevent exit 128 if no changes
          git diff-index --quiet HEAD || git commit -m "Deploy"
          
      - name: Push
        run: git push